// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['controller']['M3U8App']['CancelDownload'](arg1);
}

export function DownloadM3U8(arg1, arg2, arg3) {
  return window['go']['controller']['M3U8App']['DownloadM3U8'](arg1, arg2, arg3);
}

export function ProbeM3U8URL(arg1) {
  return window['go']['controller']['M3U8App']['ProbeM3U8URL'](arg1);
}

export function SelectOutputDir() {
  return window['go']['controller']['M3U8App']['SelectOutputDir']();
}

export function Startup(arg1) {
  return window['go']['controller']['M3U8App']['Startup'](arg1);
}
