// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {media} from '../models';
import {context} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function DownloadM3U8(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ProbeM3U8URL(arg1:string):Promise<media.MediaInfo>;

export function SelectOutputDir():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
