// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelMediaTask(arg1) {
  return window['go']['controller']['MediaApp']['CancelMediaTask'](arg1);
}

export function CheckInputFile(arg1) {
  return window['go']['controller']['MediaApp']['CheckInputFile'](arg1);
}

export function ConvertSubtitle(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['MediaApp']['ConvertSubtitle'](arg1, arg2, arg3, arg4);
}

export function ExtractSubtitle(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['controller']['MediaApp']['ExtractSubtitle'](arg1, arg2, arg3, arg4, arg5);
}

export function ScanSubtitles(arg1) {
  return window['go']['controller']['MediaApp']['ScanSubtitles'](arg1);
}

export function Startup(arg1) {
  return window['go']['controller']['MediaApp']['Startup'](arg1);
}

export function SubmitMediaTask(arg1) {
  return window['go']['controller']['MediaApp']['SubmitMediaTask'](arg1);
}
