// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {media} from '../models';
import {context} from '../models';

export function CancelMediaTask(arg1:string):Promise<void>;

export function CheckInputFile(arg1:string):Promise<string>;

export function ConvertSubtitle(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExtractSubtitle(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ScanSubtitles(arg1:string):Promise<Array<media.SubtitleStream>>;

export function Startup(arg1:context.Context):Promise<void>;

export function SubmitMediaTask(arg1:media.FFmpegTask):Promise<void>;
