// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {renamer} from '../models';
import {context} from '../models';

export function ApplyRename(arg1:Array<renamer.RenamePreview>):Promise<string>;

export function PreviewRename(arg1:Array<string>,arg2:renamer.RenameRule):Promise<Array<renamer.RenamePreview>>;

export function QuickRename(arg1:string,arg2:string):Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function Startup(arg1:context.Context):Promise<void>;
