// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyRename(arg1) {
  return window['go']['controller']['RenamerApp']['ApplyRename'](arg1);
}

export function PreviewRename(arg1, arg2) {
  return window['go']['controller']['RenamerApp']['PreviewRename'](arg1, arg2);
}

export function QuickRename(arg1, arg2) {
  return window['go']['controller']['RenamerApp']['QuickRename'](arg1, arg2);
}

export function Run(arg1) {
  return window['go']['controller']['RenamerApp']['Run'](arg1);
}

export function SelectFiles() {
  return window['go']['controller']['RenamerApp']['SelectFiles']();
}

export function Startup(arg1) {
  return window['go']['controller']['RenamerApp']['Startup'](arg1);
}
