// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyRename(arg1) {
  return window['go']['main']['App']['ApplyRename'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PreviewRename(arg1, arg2) {
  return window['go']['main']['App']['PreviewRename'](arg1, arg2);
}

export function QuickRename(arg1, arg2) {
  return window['go']['main']['App']['QuickRename'](arg1, arg2);
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}
