// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {renamer} from '../models';
import {context} from '../models';
import {media} from '../models';

export function ApplyRename(arg1:Array<renamer.RenamePreview>):Promise<string>;

export function CancelMediaTask(arg1:string):Promise<void>;

export function CheckInputFile(arg1:string):Promise<string>;

export function ExtractSubtitle(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function PreviewRename(arg1:Array<string>,arg2:renamer.RenameRule):Promise<Array<renamer.RenamePreview>>;

export function QuickRename(arg1:string,arg2:string):Promise<string>;

export function Run(arg1:context.Context):Promise<void>;

export function ScanSubtitles(arg1:string):Promise<Array<media.SubtitleStream>>;

export function SelectFiles():Promise<Array<string>>;

export function SubmitMediaTask(arg1:media.FFmpegTask):Promise<void>;
